//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitch
    {
        public int PitchID { get; set; }
        public string PitchName { get; set; }
        public string PitchLocation { get; set; }
        public int ContactID { get; set; }
        public int BookingID { get; set; }
        public int TypeID { get; set; }
        public string Day { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual PitchType PitchType { get; set; }
    }
}
